#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
# set -o xtrace

export REQUEST_HEADER
REQUEST_HEADER="Accept: application/vnd.github.v3+json"

export SCRIPT_DIRECTORY
SCRIPT_DIRECTORY=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

export GITHUB_NETRC_FILE
GITHUB_NETRC_FILE="$SCRIPT_DIRECTORY/github.netrc"

get_body()
{
    local URL=$(</dev/stdin)

    curl \
    --request GET \
    --header "$REQUEST_HEADER" \
    --netrc-file "$GITHUB_NETRC_FILE" \
    --silent \
    --show-error \
    --fail \
    "$URL" \
    | jq --join-output
}

if [ "$0" = "${BASH_SOURCE[0]}" ] ; then
    echo "$@" | get_body
fi
