#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
# set -o xtrace

source helpers/get-body
source helpers/get-header

export SRV
SRV="https://api.github.com"

export USER
USER="prominic"

export REPO
REPO="SwitchBoard-Internal-Use-Only"

deploy()
{
    #local RUN_ID="568029177"

    echo "568029177" \
    | build_artifacts_url \
    | get_body \
    | jq -j ".artifacts[0]" \
    | jq -j ".archive_download_url" \
    | get_header \
    | grep --ignore-case "location:" \
    | awk '{print $2}' \
    | download_artifact
}

build_run_url()
{
    local RUN_ID=$(</dev/stdin)
    
    echo "${SRV}/repos/${USER}/${REPO}/actions/runs/${RUN_ID}"
}

build_artifacts_url()
{
    local RUN_ID=$(</dev/stdin)
    
    echo "${SRV}/repos/${USER}/${REPO}/actions/runs/${RUN_ID}/artifacts"
}

download_artifact()
{
    local DOWNLOAD_URL=$(</dev/stdin)
    
    wget "$DOWNLOAD_URL" -O artifact.zip
}

deploy "$@"